apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kometa.fullname" . }}
  labels:
    {{- include "kometa.labels" . | nindent 4 }}
data:
  config.yml: |
{{- tpl (toYaml .Values.kometa.config) . | nindent 4 }}