{{- if .Values.envVarsSecret -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kometa.fullname" . }}
  labels:
    {{- include "kometa.labels" . | nindent 4 }}
data:
{{- range $k, $v := .Values.envVarsSecret }}
  "{{ $k }}": {{ printf "%v" $v | b64enc }}
{{- end }}
{{ end }}