apiVersion: v2
appVersion: 5.19.3
home: https://github.com/Radarr/Radarr
description: A fork of Sonarr to work with movies Ã  la Couchpotato
name: radarr
version: 1.6.0
dependencies:
  - name: helmet
    version: 0.6.5
    repository: https://companyinfo.github.io/helm-charts
    import-values:
      - defaults
