apiVersion: v2
appVersion: 2.2.2
description: Kometa is a powerful tool designed to give you complete control over your media libraries. With Kometa, 
  you can take your customization to the next level, with granular control over metadata, collections, overlays, 
  and much more.
name: kometa
version: 1.0.1
